### ISSUE TITLE
When a ghost block is placed and a creeper explosion happens near to it the ghost block will teleport somewhere random in the air or on ground sometimes

### ISSUE THREAD

**Issue by Noobymen** [GallowsDove/FoxyMachines#44] opened 2022-01-24 15:43 UTC
## Environment (Required)

 - Minecraft Version:1.18.1
 - CS-CoreLib Version:----
 - Slimefun Version: DEV 999
 - Plugin Version: DEV 53
![2022-01-24_16 43 09](https://user-images.githubusercontent.com/98334209/150815171-60570bf8-b8bb-46d7-bb55-f473192183b4.png)

**Comment by Noobymen** [comment] 2022-01-30 12:35
can i please get a reply or something if this will be looked at?

**Comment by GallowsDove** [comment] 2022-05-08 20:14
Duplicate of #53

**Closed as completed by GallowsDove** 2022-05-08 20:14 UTC
Labels: bug
