### ISSUE TITLE
too powerful

### ISSUE THREAD

**Issue by RIPISDRAD** [GallowsDove/FoxyMachines#27] opened 2021-04-22 11:20 UTC
i dont know what was ur intentions was but here are some of things i thought was wrong so just clear me or fix it (if im wrong or it was a mistake)
at first i need to know that ur plugin should provide the ultimate armor or infinity?
at second i need to know foxy sword is better than infinity?(its kinda make full set infinity guys killable)
1-the egg that spawns the vex(is too powerfull)
it litrally one tabbed(killed him with just one attack) the guy who has ur full armor set on him (i did try it with inifinity armor after the first attack i got 2 hearts left lol)that is super power of the vex
2-spawn egg of headless horseman that guys litrally pissed us off cause come on man wt frick it is, that u can only kill it with foxy sword no others we actually make an sharpness 10000 jff and it does nothing like its a wooden sword
and that guy got a lot of health and dont even let me start on hell dogs those guys kill me with full infinity armor like it was nothing (and it teleports so basically u cant trap it or do sth to kill it cause its kinda impossible one mistake ur dead)
(im not saying to delete ur ideas those are great but make it balance people really can not kill this one unless they think about it like 2h and then fight it and have a pvp god beside him)
btw there is 2 things i didnt undrestand after defeating those, they drop sth that is making strength and heart boost
which i tested both and personally dont think they really deserved to get 10min strength 4 after defeating that boss(its way less than i imagined) and health boost is same but doesnt work (is makes half of ur heart empty if u are full heart and adds nothing to u) , if there is sth else u can make by them plz tell me so i know
thats all of my questions have fun bye

**Comment by RIPISDRAD** [comment] 2021-04-22 11:21
oh this is information i can provide btw
![2021-04-19_21 11 54](https://user-images.githubusercontent.com/76468672/115706160-94a74c00-a382-11eb-8c07-91bf58095547.png)
![2021-04-19_21 11 22](https://user-images.githubusercontent.com/76468672/115706169-97a23c80-a382-11eb-8458-cc7322a52b50.png)
![2021-04-19_21 09 37](https://user-images.githubusercontent.com/76468672/115706175-98d36980-a382-11eb-9dac-5aad24e63272.png)
![2021-04-18_15 39 16](https://user-images.githubusercontent.com/76468672/115706179-996c0000-a382-11eb-814d-dc104af72840.png)
![2021-04-18_15 39 07](https://user-images.githubusercontent.com/76468672/115706181-9a049680-a382-11eb-92d5-899212a1e50b.png)

**Comment by GallowsDove** [comment] 2021-04-22 11:42
Honestly it sounds like you have some other plugin messing with the mobs, as it shouldn't deal as much damage as you've described. It would probably help if you could provide also other plugins that you have installed.
The swords are better on purpose but that's only because infinity sword is quite bad since it only provides enchants.

**Comment by RIPISDRAD** [comment] 2021-04-23 21:05
I dont think there is any we already got some but we deleted them so
basically we got if u could try it urself it would means a lot thank you

**Comment by RIPISDRAD** [comment] 2021-04-23 21:06
But still will provide u them

**Comment by GallowsDove** [comment] 2021-04-23 21:12
I, unfortunately, can't reproduce this, if you could try having nothing but slimefun and foxymachines installed on some test server and could replicate the behavior then I could work on a fix. But I don't know how to currently replicate it.

**Comment by RIPISDRAD** [comment] 2021-04-23 21:19
I know what are u saying but it happens suddenly it is not a regular thing
so it might be 10days or more or less even i got no idea

**Comment by GallowsDove** [comment] 2021-04-28 15:31
I am closing this as the required info was not provided

**Closed as completed by GallowsDove** 2021-04-28 15:31 UTC
Labels: question
