### ISSUE TITLE
Could not pass event VehicleMoveEvent

### ISSUE THREAD

**Issue by HydroGest** [GallowsDove/FoxyMachines#85] opened 2024-06-23 05:44 UTC
```
[05:42:28 ERROR]: Could not pass event VehicleMoveEvent to FoxyMachines vBuild 28 (git 98b4985)
java.lang.IllegalStateException: Unable to access unloaded data!
        at com.xzavier0722.mc.plugin.slimefun4.storage.controller.ASlimefunDataContainer.checkData(ASlimefunDataContainer.java:55) ~[sf.jar:?]
        at com.xzavier0722.mc.plugin.slimefun4.storage.controller.ASlimefunDataContainer.getData(ASlimefunDataContainer.java:72) ~[sf.jar:?]
        at com.xzavier0722.mc.plugin.slimefun4.storage.util.StorageCacheUtils.getData(StorageCacheUtils.java:49) ~[sf.jar:?]
        at me.gallowsdove.foxymachines.listeners.BoostedRailListener.onRailUse(BoostedRailListener.java:22) ~[FoxyMachines-Build 28 (git 98b4985) (1).jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.17.1.jar:git-Purpur-1428]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.world.entity.vehicle.AbstractMinecart.tick(AbstractMinecart.java:430) ~[app:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1204) ~[app:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$7(ServerLevel.java:802) ~[app:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:781) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1652) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:528) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1507) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1300) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by JustAHuman-xD** [comment] 2024-07-19 21:41
Looks like a custom slimefun version is the cause and therefor unsupported, I could *possibly* look into fixing it but I'd need you to link that slimefun

**Comment by ybw0014** [comment] 2024-08-06 02:15
this error msg is from simplified chinese version (https://github.com/SlimefunGuguProject/Slimefun4). it needs a fix on our fork. u can close this.

**Closed as completed** 2024-08-06 04:28 UTC
Labels: bug
