### ISSUE TITLE
Error in console log after using the Sweet Berry Bush trimmer

### ISSUE THREAD

**Issue by Boomer-1** [GallowsDove/FoxyMachines#14] opened 2021-02-27 21:33 UTC
## Description (Required)

After using the new berry bush trimmer i got these errors in the log.

## Steps to reproduce the Issue (Required)

trim a bush, walk into it, check the console.

## Expected behavior (Required)

not sure as i dont know what the error is 

## Server Log / Error Report

https://pastebin.com/p1FcBTfz

## Environment (Required)

 - Minecraft Version:1.16.5
 - CS-CoreLib Version: removed
 - Slimefun Version:822
 - Plugin Version: Dev 17

**Comment by GallowsDove** [comment] 2021-02-28 00:25
Should be fixed in 18, please test it and close if it no longer appears

**Comment by GallowsDove** [comment] 2021-02-28 18:25
Can't reproduce in 18, im closing the issue

**Closed as completed by GallowsDove** 2021-02-28 18:25 UTC
Labels: bug
